swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /auth/login:
    post:
      tags:
      - auth
      description: 用户登录
      operationId: AuthController.登录
      parameters:
      - in: body
        name: body
        description: 用户登录参数
        schema:
          $ref: '#/definitions/models.User'
      responses:
        helper.NOT_EXIST_FAILED:
          description: '{object} helper.RestfulReturn 用户不存在'
        helper.PASSWORD_ERROR:
          description: '{object} helper.RestfulReturn 密码错误'
        helper.SQL_ERROR:
          description: '{object} helper.RestfulReturn 登录失败'
        helper.SUCCESS:
          description: ""
          schema:
            $ref: '#/definitions/models.User'
  /auth/register:
    post:
      tags:
      - auth
      description: 用户注册
      operationId: AuthController.注册
      parameters:
      - in: body
        name: body
        description: 用户注册
        schema:
          $ref: '#/definitions/models.User'
      responses:
        helper.EXIST_FAILED:
          description: '{object} helper.RestfulReturn 用户名已存在'
        helper.REPASSWORD_FAIELD:
          description: '{object} helper.RestfulReturn 两次密码不一致'
        helper.SQL_ERROR:
          description: '{object} helper.RestfulReturn 注册失败'
        helper.SUCCESS:
          description: ""
          schema:
            $ref: '#/definitions/models.User'
  /room/get_all_room:
    get:
      tags:
      - room
      description: 获取全部房间
      operationId: WebSocketController.获取全部房间
      responses:
        helper.SQL_ERROR:
          description: '{object} helper.RestfulReturn'
        helper.SUCCESS:
          description: ""
          schema:
            $ref: '#/definitions/helper.RestfulReturn'
  /room/get_room_member:
    get:
      tags:
      - room
      description: 获取房间成员
      operationId: WebSocketController.获取房间成员
      parameters:
      - in: body
        name: body
        description: 房间ID
        schema:
          $ref: '#/definitions/.Room'
      responses:
        helper.SQL_ERROR:
          description: '{object} helper.RestfulReturn'
        helper.SUCCESS:
          description: ""
          schema:
            $ref: '#/definitions/helper.RestfulReturn'
  /room/hand:
    get:
      tags:
      - room
      description: 握手
      operationId: WebSocketController.握手
      parameters:
      - in: body
        name: body
        description: 啊啊啊
        schema:
          $ref: '#/definitions/.Room'
      responses:
        helper.SQL_ERROR:
          description: '{object} helper.RestfulReturn "加入失败"'
        helper.SUCCESS:
          description: '"加入成功"'
          schema:
            $ref: '#/definitions/helper.RestfulReturn'
  /user/update_avatar:
    post:
      tags:
      - user
      description: 修改头像
      operationId: UserController.修改头像
      parameters:
      - in: body
        name: body
        description: 头像地址
        schema:
          $ref: '#/definitions/models.User'
      responses:
        helper.SQL_ERROR:
          description: '{object} helper.RestfulReturn 修改失败'
        helper.SUCCESS:
          description: ""
          schema:
            $ref: '#/definitions/models.User'
  /wx/login:
    post:
      tags:
      - wx
      description: 微信 login
      operationId: WeChatController.微信 login
      parameters:
      - in: body
        name: body
        description: WxData
        schema:
          $ref: '#/definitions/.WxData'
      responses:
        helper.SQL_ERROR:
          description: '{object} helper.RestfulReturn 登陆失败'
        helper.SUCCESS:
          description: ""
          schema:
            $ref: '#/definitions/models.User'
  /wx/regist:
    post:
      tags:
      - wx
      description: 微信注册
      operationId: WeChatController.微信注册
      parameters:
      - in: body
        name: body
        description: WxData
        schema:
          $ref: '#/definitions/.WxData'
      responses:
        helper.SQL_ERROR:
          description: '{object} helper.RestfulReturn 登陆失败'
        helper.SUCCESS:
          description: ""
          schema:
            $ref: '#/definitions/models.User'
definitions:
  .Conn:
    type: object
  .Room:
    type: object
  .WxData:
    type: object
  .false:
    type: object
  helper.RestfulReturn:
    title: RestfulReturn
    type: object
    properties:
      Data:
        $ref: '#/definitions/989.0x11d91920.false'
      Message:
        type: string
      Result:
        $ref: '#/definitions/helper.Status'
  helper.Status:
    type: object
  models.User:
    title: User
    type: object
    properties:
      avatar:
        type: string
      conn:
        $ref: '#/definitions/websocket.Conn'
      delete_time:
        type: string
        format: string
      last_login:
        type: string
        format: string
      name:
        type: string
      nick_name:
        type: string
      password:
        type: string
      re_password:
        type: string
      token:
        type: string
      uid:
        type: integer
        format: int64
      wx_id:
        type: string
tags:
- name: auth
  description: |
    登录注册
- name: user
  description: |
    用户类
- name: room
  description: |
    WebSocketController
- name: wx
  description: |
    微信类
